site_name: TOTVS INTERFACE ROBOT
theme:
  name: material
  language: pt
  palette:
    primary: light blue
    accent: light blue
  logo: images/RoboCor.png
  favicon: images/icon-128.png

nav:
    - Bem-vindo ao TOTVS Interface Robot : 'index.md'
    - 'Processo de Teste':
      - 'Introdução a Testes': './testes/IntroduçãoaTestedeSoftware.md'
      # - 'Introdução a Testes de Software': './testes/ProcessodeTeste.md'
      # - 'Automação': './testes/Automação.md'
    - TIR: TIR.md
    - 'TIR Record':
      - 'Introdução': './tir-record/introducaoTirRecord.md'
      - 'Guia do usuário': './tir-record/ComoUsar.md'
    - 'Dashboard de Testes':
       - 'Introdução': './dashboard/index.md'
       - 'Instalação do Serviço': './dashboard/BackEnd.md'
       - 'Instalação do Portal': './dashboard/FrontEnd.md'
       - 'Guia do usuário': './dashboard/ComoUsar.md'
    - FAQ: faqGeral.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
