site_name: TEST INTERFACE ROBOT
theme:
  name: material
  language: pt
  palette:
    primary: light blue
    accent: light blue
  logo: images/RoboCor.png
  favicon: images/icon-128.png

nav:
    - Bem vindo ao Test Interface Robot : 'index.md'
    - 'Processo de Teste':
      - 'Introdução a Testes': './testes/IntroduçãoaTestedeSoftware.md'
    - 'TIR': 
      - 'Introdução': 'TIR.md'
      - 'Primeiros Passos': './tir-framework/FirstSteps.md'
      - 'Execução via Docker': './tir-framework/ExecDocker.md'
    - 'TIR Record':
      - 'Introdução': './tir-record/introducaoTirRecord.md'
      - 'Guia do usuário': './tir-record/ComoUsar.md'
      - TIR Record FAQ: 'tir-record/faq.md'
    - 'Dashboard de Testes':
       - 'Introdução': './dashboard/index.md'
       - 'Instalação': './dashboard/BackEnd.md'
       - 'Instalação via Docker': './dashboard/docker.md'       
       - 'Configuração do TIR': './dashboard/configurandoTIR.md'
       - 'Guia do usuário': './dashboard/ComoUsar.md'
    - DashBoard: 'DashBoard.md'
    - 'Testes':
      - 'Automação': 'testes/Automação.md'
      - 'Base de Dados': 'testes/BasedeDados.md'
      - 'Em Construção': 'testes/EmConstrucao.md'
      - 'Processo de Teste': 'testes/ProcessodeTeste.md'
    - FAQ: faqGeral.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
