site_name: TOTVS INTERFACE ROBOT
theme:
  name: material
  language: pt
  palette:
    primary: light blue
    accent: light blue
  logo: images/RoboCor.png
  favicon: images/icon-128.png

nav:
    - INTRODUÇÃO A TESTES: 'index.md'
    - 'TESTES':
      - 'Processo de Testes': './testes/ProcessodeTeste.md'
      - 'Automação': './testes/Automação.md'
      - 'Base de Dados': './testes/BasedeDados.md'
    - TIR: TIR.md
    - 'TIR RECORD':
      - 'Introdução': './tir-record/introducaoTirRecord.md'
      - 'Guia do usuário': './tir-record/ComoUsar.md'
      - 'FAQ': './tir-record/faq.md'
    - 'Dashboard':
      - 'Introdução': './dashboard/index.md'
      - 'Instalação do Serviço': './dashboard/BackEnd.md'
      - 'Instalação do Portal': './dashboard/FrontEnd.md'
      - 'Guia do usuário': './dashboard/ComoUsar.md'
    - FAQ: faqGeral.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
